import type { Finding, ReportDiff, ScanReport, Severity } from "@context-ray/schema";

export interface TerminalOptions {
  color?: boolean;
  maxFindings?: number;
}

const ANSI = {
  reset: "\u001b[0m",
  dim: "\u001b[2m",
  cyan: "\u001b[36m",
  green: "\u001b[32m",
  yellow: "\u001b[33m",
  red: "\u001b[31m",
  bold: "\u001b[1m",
};

function tint(value: string, code: string, enabled: boolean): string {
  return enabled ? `${code}${value}${ANSI.reset}` : value;
}

function formatTokens(value: number): string {
  if (value >= 1_000) return `${(value / 1_000).toFixed(value >= 10_000 ? 1 : 2)}k`;
  return String(value);
}

function severityColor(severity: Severity): string {
  return severity === "error" ? ANSI.red : severity === "warning" ? ANSI.yellow : ANSI.cyan;
}

export function formatTerminal(report: ScanReport, options: TerminalOptions = {}): string {
  const color = options.color ?? true;
  const maxFindings = options.maxFindings ?? 20;
  const lines = [
    `${tint("CONTEXT RAY", ANSI.bold + ANSI.cyan, color)}  ${report.scan.agent} · ${report.scan.target}`,
    tint(
      `${report.scan.root} · ${report.scan.mode} · ${report.scan.durationMs} ms`,
      ANSI.dim,
      color,
    ),
    "",
    [
      `effective ${tint(formatTokens(report.summary.effectiveTokens), ANSI.bold, color)}`,
      `tools ${formatTokens(report.summary.toolSchemaTokens)}`,
      `potential waste ${tint(formatTokens(report.summary.potentialWasteTokens), ANSI.yellow, color)}`,
      `conflicts ${tint(String(report.summary.conflicts), report.summary.conflicts ? ANSI.red : ANSI.green, color)}`,
    ].join("  ·  "),
    `${report.summary.activeSources}/${report.summary.discoveredSources} sources effective · ${report.summary.mcpServers} MCP servers · ${report.summary.mcpTools} tool schemas`,
  ];

  if (report.findings.length === 0) {
    lines.push("", tint("No findings.", ANSI.green, color));
  } else {
    lines.push("", tint(`FINDINGS (${report.findings.length})`, ANSI.bold, color));
    for (const finding of report.findings.slice(0, maxFindings)) {
      const location = finding.evidence[0];
      lines.push(
        `${tint(finding.severity.toUpperCase().padEnd(7), severityColor(finding.severity), color)} ${finding.title}`,
        `        ${finding.message}`,
        location
          ? tint(
              `        ${location.path}${location.line ? `:${location.line}` : ""} · ${finding.ruleId}`,
              ANSI.dim,
              color,
            )
          : tint(`        ${finding.ruleId}`, ANSI.dim, color),
      );
    }
    if (report.findings.length > maxFindings) {
      lines.push(
        tint(
          `… ${report.findings.length - maxFindings} additional findings omitted`,
          ANSI.dim,
          color,
        ),
      );
    }
  }

  const hidden = report.coverage.filter((item) => item.status === "not-observable");
  if (hidden.length > 0) {
    lines.push("", tint("OBSERVABILITY", ANSI.bold, color));
    for (const item of hidden) lines.push(`- ${item.area}: ${item.explanation}`);
  }
  return `${lines.join("\n")}\n`;
}

export function formatJson(report: ScanReport, pretty = true): string {
  return `${JSON.stringify(report, null, pretty ? 2 : 0)}\n`;
}

function markdownFinding(finding: Finding): string {
  const location = finding.evidence[0];
  const where = location
    ? ` — \`${location.path}${location.line ? `:${location.line}` : ""}\``
    : "";
  return `- **${finding.severity.toUpperCase()} · ${finding.title}**${where}\n  ${finding.message}\n  _Fix:_ ${finding.recommendation}`;
}

export function formatMarkdown(report: ScanReport): string {
  const coverage = report.coverage
    .map((item) => `| ${item.area} | ${item.status} | ${item.explanation.replaceAll("|", "\\|")} |`)
    .join("\n");
  return `# Context Ray report

- **Agent:** ${report.scan.agent}
- **Target:** \`${report.scan.target}\`
- **Mode:** ${report.scan.mode}
- **Scan:** ${report.scan.startedAt}

## Summary

| Metric | Value |
| --- | ---: |
| Effective context | ${report.summary.effectiveTokens.toLocaleString()} tokens |
| Instructions | ${report.summary.instructionTokens.toLocaleString()} tokens |
| Tool schemas | ${report.summary.toolSchemaTokens.toLocaleString()} tokens |
| Potentially removable | ${report.summary.potentialWasteTokens.toLocaleString()} tokens |
| Conflicts | ${report.summary.conflicts} |
| High-risk permissions | ${report.summary.highRiskPermissions} |

## Findings

${report.findings.length > 0 ? report.findings.map(markdownFinding).join("\n\n") : "No findings."}

## Observability coverage

| Area | Status | Explanation |
| --- | --- | --- |
${coverage}

---

Generated by Context Ray ${report.tool.version}. Token counts are deterministic estimates, not provider billing totals.
`;
}

export interface SarifLog {
  version: "2.1.0";
  $schema: string;
  runs: Array<Record<string, unknown>>;
}

function sarifLevel(severity: Severity): "error" | "warning" | "note" {
  return severity;
}

export function toSarif(report: ScanReport): SarifLog {
  const uniqueRules = new Map(report.findings.map((finding) => [finding.ruleId, finding]));
  return {
    version: "2.1.0",
    $schema: "https://json.schemastore.org/sarif-2.1.0.json",
    runs: [
      {
        tool: {
          driver: {
            name: "Context Ray",
            version: report.tool.version,
            informationUri: "https://github.com/context-ray/context-ray",
            rules: [...uniqueRules.values()].map((finding) => ({
              id: finding.ruleId,
              shortDescription: { text: finding.title },
              fullDescription: { text: finding.message },
              help: { text: finding.recommendation },
              properties: { category: finding.category, confidence: finding.confidence },
            })),
          },
        },
        automationDetails: { id: `${report.scan.agent}/${report.scan.target}` },
        results: report.findings.map((finding) => ({
          ruleId: finding.ruleId,
          level: sarifLevel(finding.severity),
          message: { text: `${finding.message} ${finding.recommendation}` },
          locations: finding.evidence.map((evidence) => ({
            physicalLocation: {
              artifactLocation: { uri: evidence.path.replaceAll("\\", "/") },
              region: {
                ...(evidence.line ? { startLine: evidence.line } : {}),
                ...(evidence.column ? { startColumn: evidence.column } : {}),
                snippet: { text: evidence.excerpt },
              },
            },
          })),
          properties: { confidence: finding.confidence, category: finding.category },
        })),
      },
    ],
  };
}

export function formatSarif(report: ScanReport): string {
  return `${JSON.stringify(toSarif(report), null, 2)}\n`;
}

export function formatDiff(diff: ReportDiff, color = true): string {
  const signed = (value: number): string => `${value > 0 ? "+" : ""}${value.toLocaleString()}`;
  const goodWhenNegative = (value: number): string =>
    tint(signed(value), value < 0 ? ANSI.green : value > 0 ? ANSI.red : ANSI.dim, color);
  return [
    `${tint("CONTEXT RAY DIFF", ANSI.bold + ANSI.cyan, color)}  ${diff.before.scan.id} → ${diff.after.scan.id}`,
    "",
    `effective tokens  ${goodWhenNegative(diff.deltas.effectiveTokens)}`,
    `tool schemas     ${goodWhenNegative(diff.deltas.toolSchemaTokens)}`,
    `conflicts        ${goodWhenNegative(diff.deltas.conflicts)}`,
    `high-risk        ${goodWhenNegative(diff.deltas.highRiskPermissions)}`,
    `sources          ${signed(diff.deltas.sources)}`,
    "",
    `${diff.addedSourceIds.length} sources added · ${diff.removedSourceIds.length} removed`,
    `${diff.addedFindingIds.length} findings added · ${diff.resolvedFindingIds.length} resolved`,
    "",
  ].join("\n");
}

function escapeJsonForScript(report: ScanReport): string {
  return JSON.stringify(report)
    .replaceAll("<", "\\u003c")
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");
}

export function renderHtml(report: ScanReport, template: string): string {
  const marker = "window.__CONTEXT_RAY_REPORT__ = null;";
  if (!template.includes(marker)) {
    throw new Error(`HTML template is missing the report marker: ${marker}`);
  }
  return template.replace(
    marker,
    `window.__CONTEXT_RAY_REPORT__ = ${escapeJsonForScript(report)};`,
  );
}
