const base = {
  agent: "codex",
  observability: "observed",
  confidence: "high",
  bytes: 1000,
  lines: 24,
  contentHash: "demo",
};

function source(id, label, path, kind, tokens, relevance, group, metadata = {}) {
  return {
    ...base,
    id,
    label,
    path,
    kind,
    tokenEstimate: tokens,
    relevance,
    status: metadata.loadMode === "On-demand" ? "on-demand" : "active",
    reason: metadata.reason ?? "Discovered in repository context configuration.",
    metadata: { uiGroup: group, ...metadata },
  };
}

export const demoReport = {
  schemaVersion: 1,
  tool: { name: "context-ray", version: "0.1.0" },
  scan: {
    id: "demo-context-profile",
    startedAt: "2026-07-13T06:32:00.000Z",
    durationMs: 842,
    root: "acme/checkout",
    target: "services/payments/",
    agent: "codex",
    mode: "static",
  },
  summary: {
    effectiveTokens: 48300,
    instructionTokens: 12800,
    skillTokens: 10700,
    toolSchemaTokens: 22400,
    potentialWasteTokens: 19200,
    conflicts: 3,
    highRiskPermissions: 0,
    activeSources: 19,
    discoveredSources: 25,
    mcpServers: 6,
    mcpTools: 6,
  },
  coverage: [
    { area: "repository", status: "complete", explanation: "Repository observed" },
    { area: "runtime", status: "partial", explanation: "Runtime partially observable" },
    {
      area: "internal-prompt",
      status: "not-observable",
      explanation: "Provider system prompt and prompt rewriting remain unobservable.",
    },
  ],
  sources: [
    source(
      "agents-root",
      "/AGENTS.md (root)",
      "/AGENTS.md",
      "instruction",
      5600,
      "high",
      "Instructions",
      {
        recommendation: "Keep",
        recommendationDetail: "Core instructions",
        description: "Repository-wide engineering and safety guidance.",
        reason: "Loaded from repository root for every target.",
      },
    ),
    source(
      "agents-services",
      "/services/AGENTS.md",
      "/services/AGENTS.md",
      "instruction",
      3800,
      "medium",
      "Instructions",
      {
        recommendation: "Keep",
        recommendationDetail: "Service scope rules",
        description: "Shared service implementation conventions.",
        reason: "Loaded from the parent directory of the selected target.",
      },
    ),
    source(
      "agents-payments",
      "/services/payments/AGENTS.md",
      "/services/payments/AGENTS.md",
      "instruction",
      3400,
      "high",
      "Instructions",
      {
        hideFromTable: true,
        recommendation: "Keep",
        recommendationDetail: "Target-specific rules",
        description: "Payment-domain constraints and verification commands.",
        reason: "Loaded from the selected target directory.",
      },
    ),
    source(
      "skill-testing",
      "testing.md",
      ".claude/skills/testing.md",
      "skill",
      2100,
      "high",
      "Skills",
      { loadMode: "On-demand" },
    ),
    source(
      "skill-security",
      "security.md",
      ".claude/skills/security.md",
      "skill",
      2000,
      "medium",
      "Skills",
      { loadMode: "On-demand" },
    ),
    source(
      "skill-db",
      "db-patterns.md",
      ".claude/skills/db-patterns.md",
      "skill",
      1900,
      "medium",
      "Skills",
      { loadMode: "On-demand" },
    ),
    source(
      "skill-api",
      "api-design.md",
      ".claude/skills/api-design.md",
      "skill",
      1600,
      "low",
      "Skills",
      { loadMode: "On-demand" },
    ),
    source(
      "skill-observe",
      "observability.md",
      ".claude/skills/observability.md",
      "skill",
      1600,
      "low",
      "Skills",
      { loadMode: "On-demand" },
    ),
    source(
      "skill-errors",
      "error-handling.md",
      ".claude/skills/error-handling.md",
      "skill",
      1500,
      "medium",
      "Skills",
      { loadMode: "On-demand" },
    ),
    source(
      "tool-postgres",
      "postgres-admin / query_database",
      ".mcp.json#postgres-admin/query_database",
      "mcp-tool",
      8200,
      "low",
      "MCP",
      {
        serverName: "postgres-admin",
        toolName: "query_database",
        recommendation: "Progressive discovery",
        recommendationDetail: "Est. save 5.6k (68%)",
        savings: 5600,
        description:
          "Tool schema for executing read-only SQL queries against Postgres. Includes parameter definitions, result shape, error codes, and examples.",
        reason: "Eagerly included by .mcp.json in the repository root.",
        evidence: [
          "No direct references in services/payments/",
          "Not used in recent agent sessions (last 30 days)",
          "Similar tools available via on-demand discovery",
        ],
      },
    ),
    source(
      "tool-stripe",
      "stripe / list_resources",
      ".mcp.json#stripe/list_resources",
      "mcp-tool",
      4100,
      "low",
      "MCP",
      {
        serverName: "stripe",
        toolName: "list_resources",
        recommendation: "Progressive discovery",
        recommendationDetail: "Est. save 2.7k (66%)",
        savings: 2700,
        description: "Enumerates Stripe resources and their available operations.",
      },
    ),
    source(
      "tool-redis",
      "redis / inspect_key",
      ".mcp.json#redis/inspect_key",
      "mcp-tool",
      2700,
      "low",
      "MCP",
      {
        serverName: "redis",
        toolName: "inspect_key",
        loadMode: "On-demand",
        recommendation: "Lazy (keep on-demand)",
        recommendationDetail: "Est. save 1.1k (42%)",
        savings: 1100,
      },
    ),
    source(
      "tool-s3",
      "s3 / list_objects",
      ".mcp.json#s3/list_objects",
      "mcp-tool",
      2300,
      "medium",
      "MCP",
      { serverName: "s3", toolName: "list_objects", hideFromTable: true },
    ),
    source(
      "tool-slack",
      "slack / post_message",
      ".mcp.json#slack/post_message",
      "mcp-tool",
      1800,
      "low",
      "MCP",
      { serverName: "slack", toolName: "post_message" },
    ),
    source(
      "tool-github",
      "github / search_code",
      ".mcp.json#github/search_code",
      "mcp-tool",
      1300,
      "medium",
      "MCP",
      { serverName: "github", toolName: "search_code" },
    ),
    source(
      "ref-index",
      "services/payments/src/index.ts",
      "services/payments/src/index.ts",
      "referenced-file",
      2100,
      "high",
      "References",
      { recommendation: "Keep", recommendationDetail: "Entry point" },
    ),
    source(
      "ref-db",
      "services/payments/src/db/client.ts",
      "services/payments/src/db/client.ts",
      "referenced-file",
      1800,
      "high",
      "References",
    ),
    source(
      "ref-transactions",
      "services/payments/src/transactions.ts",
      "services/payments/src/transactions.ts",
      "referenced-file",
      1700,
      "high",
      "References",
    ),
    source(
      "ref-models",
      "services/payments/src/models/*.ts",
      "services/payments/src/models/*.ts",
      "referenced-file",
      1600,
      "high",
      "References",
    ),
    source(
      "ref-types",
      "services/payments/src/types.ts",
      "services/payments/src/types.ts",
      "referenced-file",
      1400,
      "high",
      "References",
    ),
    source(
      "ref-more",
      "+121 files",
      "services/payments/src/**",
      "referenced-file",
      5500,
      "medium",
      "References",
    ),
    source(
      "conflict-agent",
      "AGENTS.md ↔ .claude/skills/",
      "AGENTS.md",
      "instruction",
      0,
      "unknown",
      "Conflicts",
      { conflict: "Conflicting guidance" },
    ),
    source(
      "conflict-env",
      "Env: DATABASE_URL",
      ".env.example",
      "config",
      0,
      "unknown",
      "Conflicts",
      { conflict: "local vs .env.example" },
    ),
    source(
      "conflict-mcp",
      "MCP server: postgres-admin",
      ".mcp.json",
      "mcp-config",
      0,
      "unknown",
      "Conflicts",
      { conflict: "duplicate config" },
    ),
    source("mcp-config", ".mcp.json", ".mcp.json", "mcp-config", 0, "high", "Configuration"),
  ],
  edges: [],
  findings: [
    {
      id: "conflict-1",
      ruleId: "conflict/guidance",
      title: "Conflicting guidance",
      message: "AGENTS.md and a skill disagree about database access.",
      severity: "error",
      confidence: "high",
      category: "conflict",
      evidence: [
        {
          sourceId: "conflict-agent",
          path: "AGENTS.md",
          line: 18,
          excerpt: "Use the service repository layer",
        },
      ],
      recommendation: "Keep the repository policy in one authoritative source.",
    },
    {
      id: "conflict-2",
      ruleId: "conflict/environment",
      title: "Environment mismatch",
      message: "DATABASE_URL differs between local guidance and .env.example.",
      severity: "warning",
      confidence: "high",
      category: "conflict",
      evidence: [
        { sourceId: "conflict-env", path: ".env.example", line: 4, excerpt: "DATABASE_URL=..." },
      ],
      recommendation: "Document one environment contract.",
    },
    {
      id: "conflict-3",
      ruleId: "mcp/duplicate-server",
      title: "Duplicate MCP server",
      message: "postgres-admin is declared twice.",
      severity: "warning",
      confidence: "high",
      category: "conflict",
      evidence: [
        { sourceId: "conflict-mcp", path: ".mcp.json", line: 2, excerpt: "postgres-admin" },
      ],
      recommendation: "Keep one declaration.",
    },
  ],
  recommendations: [
    {
      id: "recommend-postgres",
      title: "Progressive discovery",
      description:
        "Discover and load this tool only when user intent indicates database inspection is needed.",
      confidence: "medium",
      estimatedTokenSavings: 5600,
      sourceIds: ["tool-postgres"],
    },
  ],
};
